### ISSUE TITLE
Base color white gives red tiles

### ISSUE THREAD

**Issue by risoldi** [arscan/encom-globe#8]
Hi,

first of all, this is great! :)
I tried changing the baseColor, but I saw that, while it behaves correctly for most colors (i.e., if I give a blue I get blue tiles etc), when I give #ffffff I end up getting red tiles. Any idea why this is happening?
Thanks,
M.

**Comment by arscan** [comment]
Thanks, glad you like it :)  

In order to mimic the colors in the globe in the movie, I added this:

```javascript
baseColorSet = pusherColor(this.baseColor).hueSet();

var myColors = [];
for(var i = 0; i< baseColorSet.length; i++){
  myColors.push(baseColorSet[i].shade(Math.random()/3.0));
}
```

https://github.com/arscan/encom-globe/blob/master/src/Globe.js#L120

That basically processes the color that was passed in and randomly alters it slightly to make the globe a bit more interesting.

Unfortunately, this doesn't seem to work when you pass in white (probably because a hueset makes no sense for white?)

In playing around with it, I found that passing in #000000 for baseColor gives the globe a greyscale look.  Is that what you are looking for, or do you want uniformly white?  That would require changing the source code, either by me adding an option to the constructor, or you manually changing the code on your side to just have white in the myColors array.

**Comment by risoldi** [comment]
A-ha, I see! I like the hues, I will just need to reduce the range a little from white to medium-light-grey. It's easy to modify that bit of code once it's clear what it does. Thanks!
